FROM 763104351884.dkr.ecr.us-east-1.amazonaws.com/tensorflow-inference:2.12.1-cpu

ADD ./requirements.inference.txt /opt/ml/code/requirements.inference.txt
RUN pip install -r /opt/ml/code/requirements.inference.txt
 

ADD ./inference.py /opt/ml/code/inference.py


ENV FLASK_APP=/opt/ml/code/inference.py
CMD ["flask", "run", "--host", "0.0.0.0", "--port", "8080"]